[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/portfolio"
  to = "/.netlify/functions/portfolio-page"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio/*"
  to = "/.netlify/functions/portfolio-page"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

