[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/portfolio"
  to = "/.netlify/functions/portfolio-page"
  status = 200
  force = true

[[redirects]]
  from = "/portfolio/*"
  to = "/.netlify/functions/portfolio-page"
  status = 200
  force = true

[[redirects]]
  from = "/pips/*"
  to = "/pips/frontend/dist/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

